#!/usr/bin/env bash
# script that transfers a file from our client to a serve
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4
if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -gt 3 ]; then
	scp -o StrictHostKeyChecking=no -i $ssh_key_path $file_path $username@$server_ip:~/
else
	scp -o StrictHostKeyChecking=no $file_path $username@$server_ip:~/
fi
