#!/usr/bin/env bash
# Script that installs nginx on Ubuntu machine
apt-get -y update
apt-get -y install nginx

# echo "Hello World!" > /var/www/html/index.nginx-debian.html
# service nginx start

service nginx start

sed -i 's/#listen 80;/listen 80;/g' /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.html
