#!/usr/bin/env bash
# Configure your Nginx server to redirect /redirect_me to another page.
apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

config="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "/listen 80 default_server;/a $config" /etc/nginx/sites-available/default

ufw allow 'Nginx HTTP'
service nginx restart
