#!/usr/bin/env bash
# Configure the Nginx server to have a custom 404 page
apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

config="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

error="error_page 404 /404.html;"

sed -i "/listen 80 default_server;/a $config" /etc/nginx/sites-available/default

sed -i "/listen 80 default_server;/a $error" /etc/nginx/sites-available/default

ufw allow 'Nginx HTTP'
service nginx restart
