#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

apt-get -y update
apt-get -y install nginx

config="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

error="error_page 404 /404.html;"

sed -i "/listen 80 default_server;/a $config" /etc/nginx/sites-available/default

sed -i "/listen 80 default_server;/a $error" /etc/nginx/sites-available/default

sed -i '14a \\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/nginx.conf

service nginx restart
