#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

config_file="/etc/haproxy/haproxy.cfg"

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes
backend nodes
	mode http
	balance roundrobin
	server 268033-web-01 35.237.170.121
	server 268033-web-02 100.25.38.27" >> $config_file

sudo service haproxy restart
