#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100 with conditions

idx=0

while [ $((idx++)) -lt 100 ]; do
	if [ $((idx % 15)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((idx % 5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((idx % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo $idx
	fi
done
