#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd
while IFS=':' read -r username _ uid _ home_dir _; do
    echo  "$username"
    echo  "$uid"
    echo  "$home_dir"
done < /etc/passwd
