#!/usr/bin/env bash
# This script is displaying types of luck 10 times
idx=0
while [ $((++idx)) -le 10 ]; do
	if [ $idx == 4 ];
	then
		echo "bad luck"
	elif [ $idx == 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
fi
done
