#!/usr/bin/env bash
# This script is displaying luck from countries 20 times
idx=1
while [ $idx -le 20 ]; do
	echo $idx
	case $idx in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((idx++))
done
