#!/usr/bin/env bash
# nginx running as user nginx on 8080
if ! dpkg -l | grep -q nginx; then
    apt-get update
    apt-get install -y nginx
fi
chmod 644 /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
